name: Release App

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish macOS (electron-builder)
        env:
          APPLEID_USERNAME: ${{ secrets.appleid_username }}
          APPLEID_PASSWORD: ${{ secrets.appleid_password }}
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
          GH_TOKEN: ${{ secrets.gh_token }}
          NOTARIZE: true
        run: yarn make:macos --publish always

      - name: Clean up builds
        run: rm -rfv dist/mac dist/mac-arm64

      - uses: actions/upload-artifact@v2
        with:
          name: Instatus-Out-dist-mac
          path: dist/

  release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish Windows (electron-builder)
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: yarn make:win --publish always

      - name: Clean up builds
        run: Remove-Item dist/win-unpacked -Recurse

      - uses: actions/upload-artifact@v1
        with:
          name: Instatus-Out-dist-win
          path: dist

  release-linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish Linuxs (electron-builder)
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: yarn make:linux --publish always

      - name: Clean up builds
        run: rm -rfv dist/linux-unpacked

      - uses: actions/upload-artifact@v1
        with:
          name: Instatus-Out-dist-linux
          path: dist